version: 2

before:
  hooks:
builds:
- env:
  - CGO_ENABLED=0
  goos:
    - linux
  goarch:
    - amd64
    - arm64
  dir: ./cmd/hranoprovod-cli
  binary: hranoprovod-cli

archives:
-
checksum:
  name_template: 'checksums.txt'
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
nfpms:
-
  vendor: "avtobiografia.com"
  homepage: "https://github.com/aquilax/hranoprovod-cli"
  maintainer: "Evgeniy Vasilev <aquilax@gmail.com>"
  description: "Command line life tracking tool"
  license: "MIT"
  formats:
    - deb
    - rpm
