# This is an example goreleaser.yaml file with some sane defaults.
# Make sure to check the documentation at http://goreleaser.com
before:
  hooks:
builds:
- env:
  - CGO_ENABLED=0
  goos:
    - linux
  goarch:
    - amd64

archives:
- replacements:
    linux: Linux
    windows: Windows
    386: i386
    amd64: x86_64
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
snapcrafts:
-
  summary: Life metrics plaintext tracker
  publish: true
  grade: devel
  confinement: devmode
  description: |
    Hranoprovod is command line tracking tool. It supports nested recipes and custom defined tracking elements, which makes it perfect for tracking calories, nutrition data, exercises and other accumulative data.
nfpms:
-
  vendor: "avtobiografia.com"
  homepage: "https://github.com/aquilax/hranoprovod-cli"
  maintainer: "Evgeniy Vasilev <aquilax@gmail.com>"
  description: "Command line life tracking tool"
  license: "MIT"
  replacements:
    amd64: 64bit
    386: 32bit
  formats:
    - deb
    - rpm
