name: hranoprovod-cli
version: git
summary: Life metrics plaintext tracker
description: |
  Hranoprovod is command line tracking tool. It supports nested recipes and custom defined tracking elements, which makes it perfect for tracking calories, nutrition data, exercises and other accumulative data.

grade: stable
confinement: strict
base: core18

parts:
  hranoprovod-cli:
    source: .
    plugin: go
    go-importpath: github.com/aquilax/hranoprovod-cli
    source-type: git

apps:
  hranoprovod-cli:
    command: hranoprovod-cli
    plugs: ["personal-files"]

plugs:
  personal-files:
    read:
      - $HOME/.hranoprovod/food.yaml
      - $HOME/.hranoprovod/log.yaml
      - $HOME/.hranoprovod/config
