name: hranoprovod-cli
version: git
summary: Life metrics plaintext tracker
description: |
  Hranoprovod is command line tracking tool. It supports nested recipies and custom defined tracking elements, which makes it perfect for tracking calories, nutionin data, excercises and other accumulative data.

grade: devel
confinement: devmode

parts:
  hranoprovod-cli:
    source: .
    plugin: go
    go-importpath: github.com/aquilax/hranoprovod-cli
    source-type: git

apps:
  hranoprovod-cli:
    command: hranoprovod-cli
