name: goreleaser

on:
  push:
    branches:
      - "!*"
    tags:
      - "v*.*.*"

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v1
        with:
          fetch-depth: 1
      -
        name: Set up Go
        uses: actions/setup-go@v1
        with:
          go-version: '1.18'
      -
        name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v1.0.2
        with:
          version: latest
          args: release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      -
        name: Publish to Registry
        uses: elgohr/Publish-Docker-Github-Action@v5
        with:
          name: aquilax/hranoprovod-cli
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          tag_semver: true