name: goreleaser

on:
  pull_request:
  push:

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v1
      -
        name: Set up Go
        uses: actions/setup-go@v1
        with:
          go-version: '1.13.4'
      - 
        name: Go Action
        uses: actions-contrib/go@v0.1.0
        with:
          args: test -v ./...
      -
        name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v1.0.2
        with:
          version: latest
          args: release
